### ISSUE TITLE
Game broken

### ISSUE THREAD

**Issue by migarjo** [githubschool/github-games-ea-flores#1]
When attempting to access this at https://githubschool.github.io/github-games-ea-flores, I am getting a 404. This could be caused by a couple things:

 - GitHub pages needs to be enabled on master. You can fix this in the repository settings.
- the index.html file is incorrectly named inde.html. We will fix this together in class.

 Can you please fix the first bullet @ea-flores?

**Comment by ea-flores** [comment]
both issues have been corrected and the game is now running as expected
